# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2359ed32429306754742c8de1c6ee7a01c0830a8398af498fd5b7d17b9cf164000d8db1f2c83f0a6f48b78930ab2d7f63a50c8f85144c7a2de42145c528fa16f

test:
  secret_key_base: 5baa20a7e9cc24149bec63476b81dedbedbf5a023b710d25f3bbb229c6bfe0f8f7bd15bd6b67940be3ffd75b06f9dc7b6cc57dd07ce72a58c8c43be8dfec1cd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
